version: '2'
services:
  nginx:
    restart: always
    container_name: task-nginx
    image: nginx:latest
    ports:
      - "690:80"
    volumes:
      - ./src:/src
      - ./logs/nginx/:/logs
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    links:
      - php

  php:
    restart: always
    container_name: task-php
    build: docker/php
    volumes:
      - ./src:/src
      - ./logs/php:/logs
    links:
      - postgres
    #ports:
    #  - "${WEBSOCKET_PORT}:${WEBSOCKET_PORT}"
    env_file:
      - ./.env

  postgres:
    restart: always
    container_name: task-postgres
    build: docker/postgres
    ports:
      - "5433:5432"
    volumes:
      - ./storage/postgres:/storage
    environment:
      PGDATA: '/storage'
    env_file:
      - ./.env
