<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Template</title>
        <link href="/css/bootstrap.min.css" rel="stylesheet">
        <link href="/css/pages.css" rel="stylesheet">
        <link href="/css/icons.css" rel="stylesheet">
        <link href="/css/style.css" rel="stylesheet">
        <link href="/plugins/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" rel="stylesheet">
        <link href="/plugins/bootstrap-timepicker/css/bootstrap-timepicker.css" rel="stylesheet">
        <link href="/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css" rel="stylesheet" />


        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <?php echo $this->getContent(); ?>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>
        <script src="/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js"></script>
        <script src="/plugins/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
        <script src="/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js"></script>
        <script src="/js/script.js"></script>
    </body>
</html>