<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/tasks">Task list</a></li>
                <li><a href="/add">Add task</a></li>
            </ul>

            <?php if ($this->auth->isLoggedIn('auth-admin')) { ?>
                <a href="/logout" class="btn btn-default navbar-btn pull-right">Выход</a>
                <ul class="nav navbar-nav pull-right">
                    <li >
                        <a href="/admin/tasks">admin</a>
                    </li>
                </ul>
            <?php } else { ?>
                <a href="/" class="btn btn-default navbar-btn pull-right">Войти</a>
            <?php }  ?>

        </div>
    </div>
</div>
<div class="container theme-showcase " style="padding-top: 60px;" role="main">
    <?php echo $this->getContent(); ?>
</div>

