<div class="wrapper-page">
    <div class="text-center">
        <a href="index.html" class="logo logo-lg"><span>Login</span></a>
    </div>

    <form class="form-horizontal m-t-20"
          method="post"
          action="/login">
        <div class="form-group">
            <div class="col-xs-12">
                <input class="form-control"
                       type="text"
                       required=""
                       placeholder="Username"
                       name="login" />
                <i class="md md-account-circle form-control-feedback l-h-34"></i>
            </div>
        </div>

        <div class="form-group">
            <div class="col-xs-12">
                <input class="form-control"
                       type="password"
                       required=""
                       placeholder="Password"
                       name="password" />
                <i class="md md-vpn-key form-control-feedback l-h-34"></i>
            </div>
        </div>

        <div class="form-group text-right m-t-20">
            <div class="col-xs-12">
                <button class="btn btn-primary btn-custom w-md waves-effect waves-light" type="submit">Log In
                </button>
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-12">
                <?php $this->flashSession->output();?>
            </div>
        </div>
    </form>
</div>
